[NEW] Add special koji app container
shiqimei/Rocket.Chat pull request #2
Opened 2019-06-18 14:30 UTC by lolimay

Closes #ISSUE_NUMBER

2019-06-25 11:05 UTC, kb0304 requested changes

2019-06-25 11:05 UTC, kb0304 commented on app/ui-message/client/message.js
> +	const result = msg.msg.match(/(^\$kojistart\$)(.+)(\$kojiend\$)$/);
Instead of putting this logic here, can we use the existing functionality of `MessageTypes` to check and render it like this?

2019-07-08 18:00 UTC, lolimay commented
@kb0304  Could you please review it again when you are available? Thanks!

2019-07-14 07:49 UTC, kb0304 commented on app/koji-demo/client/views/koji-demo.html
> +	<iframe src="//localhost:1234" frameborder="0" height="625"></iframe>
Why do we need to hard-code this host-name and port

2019-07-14 07:49 UTC, kb0304 commented on app/koji-demo/client/lib/miniAppMessage.js
> +			return `<iframe src=\"${ message.appUrl }\" frameborder=\"0\" height=\"533.333\"></iframe>`;
Can we handle here if the `message.appUrl` is not present, or handle it in the Meteor method?

2019-10-18 18:23 UTC, closed without merging